/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum_1;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Tugas1 extends javax.swing.JFrame {

    /**
     * Creates new form Tugas1
     */
    public Tugas1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enama = new javax.swing.JLabel();
        fnama = new javax.swing.JTextField();
        enim = new javax.swing.JLabel();
        fnim = new javax.swing.JTextField();
        efakultas = new javax.swing.JLabel();
        fprodi = new javax.swing.JComboBox<>();
        eprodi = new javax.swing.JLabel();
        ffakultas = new javax.swing.JTextField();
        egender = new javax.swing.JLabel();
        flaki = new javax.swing.JRadioButton();
        fcwek = new javax.swing.JRadioButton();
        enohp = new javax.swing.JLabel();
        fnohp = new javax.swing.JTextField();
        ealamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        falamat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        falasan = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        esimpan = new javax.swing.JButton();
        ekeluar = new javax.swing.JButton();
        eriset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel1.setText("FORMULIR PENDAFTARAN UKM-FT ITC  ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 20, 370, 24);

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel2.setText("UNIVERSITAS tRUNOJOYO MADURA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 50, 320, 24);

        enama.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        enama.setText("Nama Lengkap :");
        getContentPane().add(enama);
        enama.setBounds(6, 159, 104, 15);

        fnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnamaActionPerformed(evt);
            }
        });
        getContentPane().add(fnama);
        fnama.setBounds(128, 159, 255, 22);

        enim.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        enim.setText("NIM                    :");
        getContentPane().add(enim);
        enim.setBounds(6, 214, 102, 15);

        fnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnimActionPerformed(evt);
            }
        });
        getContentPane().add(fnim);
        fnim.setBounds(128, 214, 255, 22);

        efakultas.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        efakultas.setText("Fakultas            :");
        getContentPane().add(efakultas);
        efakultas.setBounds(8, 262, 102, 15);

        fprodi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistem Informasi", "Teknik Informatika ", "Teknik Industri", "Teknik Mekatronika", "Teknik Elektro ", "Teknik Mesin" }));
        fprodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fprodiActionPerformed(evt);
            }
        });
        getContentPane().add(fprodi);
        fprodi.setBounds(128, 298, 255, 22);

        eprodi.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        eprodi.setText("Prodi                  :");
        getContentPane().add(eprodi);
        eprodi.setBounds(8, 305, 100, 15);

        ffakultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffakultasActionPerformed(evt);
            }
        });
        getContentPane().add(ffakultas);
        ffakultas.setBounds(128, 258, 255, 22);

        egender.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        egender.setText("Jenis Kelamin  :");
        getContentPane().add(egender);
        egender.setBounds(6, 341, 94, 15);

        buttonGroup1.add(flaki);
        flaki.setText("Laki-laki");
        flaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flakiActionPerformed(evt);
            }
        });
        getContentPane().add(flaki);
        flaki.setBounds(128, 338, 98, 21);

        buttonGroup1.add(fcwek);
        fcwek.setText("Perempuan");
        getContentPane().add(fcwek);
        fcwek.setBounds(285, 338, 98, 21);

        enohp.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        enohp.setText("No HP                 :");
        getContentPane().add(enohp);
        enohp.setBounds(6, 377, 100, 15);

        fnohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnohpActionPerformed(evt);
            }
        });
        getContentPane().add(fnohp);
        fnohp.setBounds(128, 377, 255, 22);

        ealamat.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        ealamat.setText("Alamat               :");
        getContentPane().add(ealamat);
        ealamat.setBounds(7, 417, 100, 15);

        falamat.setColumns(20);
        falamat.setRows(5);
        jScrollPane1.setViewportView(falamat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(128, 407, 255, 86);

        falasan.setColumns(20);
        falasan.setRows(5);
        falasan.setText("Alasan Masuk UKM-FT ITC :");
        jScrollPane2.setViewportView(falasan);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(7, 511, 520, 125);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/praktikum_1/mahsusi.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(470, 20, 80, 79);

        jLabel12.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel12.setText("jl. Raya Telang PO.Box.2.Kamal, Bangkalan - Madura");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(130, 80, 298, 15);

        jLabel13.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel13.setText("Telp : (031) 3011146, Fax. (031) 3011506 ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(170, 100, 238, 15);

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/praktikum_1/andi.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(462, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 560, 120);

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        esimpan.setText("Simpan");
        esimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esimpanActionPerformed(evt);
            }
        });

        ekeluar.setText("Keluar");
        ekeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekeluarActionPerformed(evt);
            }
        });

        eriset.setText("Reset");
        eriset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erisetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(esimpan)
                .addGap(26, 26, 26)
                .addComponent(eriset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(ekeluar)
                .addGap(46, 46, 46))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(551, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(esimpan)
                    .addComponent(ekeluar)
                    .addComponent(eriset))
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 120, 560, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnamaActionPerformed

    private void fprodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fprodiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fprodiActionPerformed

    private void fnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnimActionPerformed

    private void ffakultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffakultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ffakultasActionPerformed

    private void flakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flakiActionPerformed

    private void fnohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnohpActionPerformed

    private void esimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esimpanActionPerformed
        String nama = fnama.getText();
        String nim = fnim.getText();
        String alamat = falamat.getText();
        String fakultas = ffakultas.getText();
        String prodi = fprodi.getSelectedItem().toString();
        flaki.setActionCommand("Laki-laki");
        fcwek.setActionCommand("Perempuan");
        String nohp = fnohp.getText();
        String alasan = falasan.getText();
        String jenis = null;
        
        if(buttonGroup1.getSelection()!=null){
            jenis = buttonGroup1.getSelection().getActionCommand();
        }
        
        
        JOptionPane.showMessageDialog(null, "Nama :" + nama + "\nNIM :" + nim + "\nAlamat :" + alamat +
                "\nFakultas : :" + fakultas + "\nProdi :" + prodi + "\nJenis Kelamin :" + jenis +"\nNo HP :" + nohp + "\nAlasan :" + alasan);
        // TODO add your handling code here:
    }//GEN-LAST:event_esimpanActionPerformed

    private void erisetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erisetActionPerformed
        // TODO add your handling code here:
        fnama.setText("");
        fnim.setText("");
        fprodi.setSelectedIndex(-1);
        buttonGroup1.clearSelection();
        falamat.setText("");
        fnohp.setText("");
        falasan.setText("");
        ffakultas.setText("");
    }//GEN-LAST:event_erisetActionPerformed

    private void ekeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekeluarActionPerformed
        JOptionPane.showMessageDialog(this,"Selesai");
        System.exit(0);
    }//GEN-LAST:event_ekeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel ealamat;
    private javax.swing.JLabel efakultas;
    private javax.swing.JLabel egender;
    private javax.swing.JButton ekeluar;
    private javax.swing.JLabel enama;
    private javax.swing.JLabel enim;
    private javax.swing.JLabel enohp;
    private javax.swing.JLabel eprodi;
    private javax.swing.JButton eriset;
    private javax.swing.JButton esimpan;
    private javax.swing.JTextArea falamat;
    private javax.swing.JTextArea falasan;
    private javax.swing.JRadioButton fcwek;
    private javax.swing.JTextField ffakultas;
    private javax.swing.JRadioButton flaki;
    private javax.swing.JTextField fnama;
    private javax.swing.JTextField fnim;
    private javax.swing.JTextField fnohp;
    private javax.swing.JComboBox<String> fprodi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
